

package ca.derekellis.workers.kotlin;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link ca.derekellis.workers.kotlin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("kotlin-plugin-tests/src/test/data/dump")
@TestDataPath("$PROJECT_ROOT")
public class DumpTestGenerated extends AbstractDumpTest {
  @Test
  public void testAllFilesPresentInDump() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("kotlin-plugin-tests/src/test/data/dump"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("kotlin-plugin-tests/src/test/data/dump/ir")
  @TestDataPath("$PROJECT_ROOT")
  public class Ir {
    @Test
    public void testAllFilesPresentInIr() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("kotlin-plugin-tests/src/test/data/dump/ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("GeneratedWorkerServiceAdapter.kt")
    public void testGeneratedWorkerServiceAdapter() {
      runTest("kotlin-plugin-tests/src/test/data/dump/ir/GeneratedWorkerServiceAdapter.kt");
    }
  }
}
