package ca.derekellis.workers.gradle

import java.io.File
import org.gradle.api.DefaultTask
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

internal abstract class WriteWebpackConfigTask : DefaultTask() {

  @get:OutputFile
  val webpackConfigFile: File by lazy { project.projectDir.resolve(generatedFilePath) }

  @get:Optional @get:Input abstract val target: Property<String>

  @TaskAction
  fun task() {
    val target = this.target.orNull

    if (target != null) {
      webpackConfigFile.parentFile.mkdirs()
      webpackConfigFile.writeText(
        """
        |// DO NOT EDIT.
        |//
        |// This file is generated by the Worker Gradle plugin. You may ignore it
        |// by adding this line to your .gitignore:
        |//
        |// generated-worker-webpack-config.js
        |//
        |config.target = "$target"
        |
        """
          .trimMargin()
      )
    } else {
      webpackConfigFile.delete()
    }
  }

  companion object {
    val generatedFilePath = "webpack.config.d/generated-worker-webpack-config.js"
  }
}
